### ISSUE TITLE
Voice Functions

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unity-TheWorldBeyond#12]
On opening the world scene it looks like the functions to activate the Voice functions are missing? There are no Focus change events or response events included on the Wit Connector. The Wit configuration is missing completely. I understand you may require us to setup our own Wit configuration as per the docs but it would be great to get some guidance of how to connect the focus change events and response events in Unity and in Wit as it is this Voice SDK related features that I am most interested in in this project. Thanks

**Comment by PanyaMeta** [comment]
Hello @owlandfox The Focus Change events are added in code when the game starts, so the Inspector list is empty. You can see how this is done in its [OnEnable method](https://github.com/oculus-samples/Unity-TheWorldBeyond/blob/main/Assets/Scripts/WitConnector.cs#L55). We have omitted the Wit config from the project, but this [setup guide](https://developer.oculus.com/documentation/unity/voice-sdk-integrate-voice/) should help!
