### ISSUE TITLE
Compilation issues in Unity 2022

### ISSUE THREAD

**Issue by vincismurf** [oculus-samples/Unity-TheWorldBeyond#14]
OculusSettings.TargetQuest no longer exist must use TargetQuest2

Int OVRDeviceSelector.isTargetDeviceQuest line 44

**Comment by PanyaMeta** [comment]
@vincismurf thank you for the find, an update has been pushed! It looks like there are a few new issues when opening in new versions of Unity. We'll resolve these shortly.
