### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by zlggithubzlg** [oculus-samples/Unity-TheWorldBeyond#4]
The World Beyond requires Scene data. Please disable Link, then run Room Setup in Settings. Then enable Link and try again.

**Comment by PanyaMeta** [comment]
Room Setup must be accomplished separately, prior to attaching your Quest via Link cable. After setting up the room, then connecting Link, will the room data be available in Editor. Please see the Scene Capture section here: https://developer.oculus.com/documentation/unity/unity-scene-overview/

"NOTE: You cannot perform Scene Capture over Meta Quest Link. You must perform Room Setup on-device prior to loading the Scene Model over Link."
