### ISSUE TITLE
Failed to initialize Insight Passthrough

### ISSUE THREAD

**Issue by Parad0x-o1** [oculus-samples/Unity-TheWorldBeyond#5]
When trying to run Unity-TheWorldBeyond Project with Quest Pro linked via cable I receive the following error in Unity:

Failed to initialize Insight Passthrough. Passthrough will be unavailable. Error Failure_NotInitialized.
UnityEngine.Debug:LogError (object)
OVRManager:InitializeInsightPassthrough () (at Assets/Oculus/VR/Scripts/OVRManager.cs:2533)
OVRManager:InitOVRManager () (at Assets/Oculus/VR/Scripts/OVRManager.cs:1735)
OVRManager:Awake () (at Assets/Oculus/VR/Scripts/OVRManager.cs:1750)

running Oculus PC App 46.0.0.229.0

Running Quest Pro OS 46.0.0.226.0.406523063

Unity Version 2022.2.0b10 (Also Verified the same error with Unity Version 2021.3.3f1)

**Comment by joejohndoe** [comment]
Did you follow the setup steps for Passthrough over Link as outlined here? Specifically, the toggles in the "Software" section? Note that you need to restart Unity after enabling those settings.

**Comment by Parad0x-o1** [comment]
> 

Looks like maybe your link did not attach? Could you re-attach and I will try.

Wouldn't all unity settings carry over when opening TheWorldBeyond project?

**Comment by joejohndoe** [comment]
Apologies: https://developer.oculus.com/documentation/unity/unity-passthrough-over-link/

> Wouldn't all unity settings carry over when opening TheWorldBeyond project?

Passthrough over Link needs to be enabled in the Oculus PC app.

**Comment by PanyaMeta** [comment]
> When trying to run Unity-TheWorldBeyond Project with Quest Pro linked via cable I receive the following error in Unity:
> 
> Failed to initialize Insight Passthrough. Passthrough will be unavailable. Error Failure_NotInitialized. UnityEngine.Debug:LogError (object) OVRManager:InitializeInsightPassthrough () (at Assets/Oculus/VR/Scripts/OVRManager.cs:2533) OVRManager:InitOVRManager () (at Assets/Oculus/VR/Scripts/OVRManager.cs:1735) OVRManager:Awake () (at Assets/Oculus/VR/Scripts/OVRManager.cs:1750)
> 
> running Oculus PC App 46.0.0.229.0
> 
> Running Quest Pro OS 46.0.0.226.0.406523063
> 
> Unity Version 2022.2.0b10 (Also Verified the same error with Unity Version 2021.3.3f1)

To confirm and close this out, do you have "Passthrough over Oculus Link" enabled in the Oculus PC app?

**Comment by Parad0x-o1** [comment]
> Apologies: https://developer.oculus.com/documentation/unity/unity-passthrough-over-link/
> 
> > Wouldn't all unity settings carry over when opening TheWorldBeyond project?
> 
> Passthrough over Link needs to be enabled in the Oculus PC app.

Finally had a chance to confirm, this resolved the issue. 

Thanks!
